services:
  app:
    build: .
    container_name: front-denuncias
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

    volumes:
      - uploads_data:/app/uploads
      - informes_data:/app/download
    restart: unless-stopped

volumes:
  uploads_data:
    driver: local
  informes_data:
    driver: local
